// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Paste struct {
	ID           int64              `json:"id"`
	Slug         string             `json:"slug"`
	Content      string             `json:"content"`
	PasswordHash *string            `json:"password_hash"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
