// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pastes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPaste = `-- name: CreatePaste :one
INSERT INTO pastes (slug, content, password_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, slug, content, password_hash, expires_at, created_at
`

type CreatePasteParams struct {
	Slug         string             `json:"slug"`
	Content      string             `json:"content"`
	PasswordHash *string            `json:"password_hash"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePaste(ctx context.Context, arg CreatePasteParams) (Paste, error) {
	row := q.db.QueryRow(ctx, createPaste,
		arg.Slug,
		arg.Content,
		arg.PasswordHash,
		arg.ExpiresAt,
	)
	var i Paste
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Content,
		&i.PasswordHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPaste = `-- name: GetPaste :one
SELECT id, slug, content, password_hash, expires_at, created_at FROM pastes
WHERE slug = $1
`

func (q *Queries) GetPaste(ctx context.Context, slug string) (Paste, error) {
	row := q.db.QueryRow(ctx, getPaste, slug)
	var i Paste
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Content,
		&i.PasswordHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
